### ISSUE TITLE
pruned nodes compatibility issue

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#29]
Ideally forkscanner will be connected to pruned btc nodes, we should have a check which ignores a block if gets pruned status back from btc node for the first get. 

right now forkscanner keeps on sending the same get block request again and again, and goes into an infinite loop and gets blocked by the btc node.

**Comment by tjsharp1** [comment]
I am not seeing this behavior, I do see the forkscanner getting a message about pruned blocks:

`JSON-RPC error for getblock: RpcError { code: -1, message: "Block not available (pruned data)", data: None }`

but it seems to continue on past this, can you describe steps to reproduce what you're seeing?
