### ISSUE TITLE
The websocket (pubsub) connection is not working.

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#32]
Trying out the validation_checks pubsub, it's not returns a random json rather than what was expected.  

<img width="1417" alt="Screenshot 2022-06-16 at 7 20 14 PM" src="https://user-images.githubusercontent.com/24653325/174091164-0e74d91a-f060-417a-b8e2-7dc582892554.png">
<img width="1417" alt="Screenshot 2022-06-16 at 7 20 38 PM" src="https://user-images.githubusercontent.com/24653325/174091186-5b3b7b08-9ef1-4440-b8c3-b0f90c4ddc65.png">

above the results i get for this `{"jsonrpc": "2.0", "id": 1, "method": "validation_checks", "params": [20]}`

what we require is the Chaintip height, stale candidate height, timestamp for stale candidate, chaintip, stalecandidate tip, branch length of stale branch and stale branch root (block where the branch started)

**Comment by tjsharp1** [comment]
That first response is giving you a subscription id, that is expected.
For the second one, did you check if there are stale candidates in the database that are within your query window? This is the expected response if there are none (an empty list).

**Comment by AhmadAshraf2** [comment]
yes you are right my stale candidates table is empty. though according to code [here](https://github.com/twilight-project/forkscanner/blob/add-inflation-checks/src/service.rs#L180) we are still missing a few details 
1. stale branch length
2. stale branch root
