### ISSUE TITLE
missing get_chaintips endpoint

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#34]
we require a web socket (pubsub). which would send a notification whenever anything changes in the chaintips table.

**Comment by tjsharp1** [comment]
There is this pubsub endpoint as well: https://github.com/twilight-project/forkscanner/blob/main/src/service.rs#L312

That will give you active chaintips, is that what you're looking for?

**Comment by AhmadAshraf2** [comment]
this gives a collection of chaintips, we need one source of truth
