### ISSUE TITLE
issues in match parent and match children methods

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#35]
https://github.com/twilight-project/forkscanner/blob/main/src/scanner.rs#L927

this check should be other way around to ensure that the relation between parent and child is correct
same goes for the method match_parent

**Comment by tjsharp1** [comment]
This is how forkmonitor implements it, pointing parent_chaintip at the most recent active tip. Do you need the reference reversed for your purposes? I can imagine there is a join query that will get what you want.
