### ISSUE TITLE
Excessive array declaration and data returned in subscribe_forks websocket response

### ISSUE THREAD

**Issue by hammadtq** [twilight-project/forkscanner#41]
I am getting this response from subscribe_forks websocket:
```
recv: {"jsonrpc":"2.0","result":10550142073689083033,"id":1}
```
```
recv: {"jsonrpc":"2.0","method":"forks","params":[[{"block":"000000000000000000023ad1f1c37363b224c11d039bd27ff9d01e734b239f2f","height":742542,"id":1,"node":1,"parent_chaintip":null,"status":"active"},{"block":"000000000000000000023ad1f1c37363b224c11d039bd27ff9d01e734b239f2f","height":742542,"id":2,"node":2,"parent_chaintip":null,"status":"active"}]]}
```

**Issue 1**
I am not able to understand what and why I am getting this:
```
recv: {"jsonrpc":"2.0","result":10550142073689083033,"id":1}
```

Can I please have just 1 response of chaintip?

**Issue 2**
```
{
	"jsonrpc": "2.0",
	"method": "forks",
	"params": [
		[{
			"block": "000000000000000000023ad1f1c37363b224c11d039bd27ff9d01e734b239f2f",
			"height": 742542,
			"id": 1,
			"node": 1,
			"parent_chaintip": null,
			"status": "active"
		}, {
			"block": "000000000000000000023ad1f1c37363b224c11d039bd27ff9d01e734b239f2f",
			"height": 742542,
			"id": 2,
			"node": 2,
			"parent_chaintip": null,
			"status": "active"
		}]
	]
}
```

Params array is actually coming in as array in an array, if there is no use-case of this, please return just one array or return just one block as the chaintip that forkoracle will use to send to the chain.

**Comment by tjsharp1** [comment]
For the first issue, that is a reply showing you your subscription id. If you wanted to unsubscribe from events, you would then use that to call unsubscribe.

I can look at the double array issue, should be straightforward.
